# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 691f09ee44a0ff6ebdb69d3c76842ac790fe87aaf67910e458405c65f70e77e5d82002bcd6a07ea9f9f4f932a519aff061cdf55910e29e01ffbf1c210be25247

test:
  secret_key_base: d9fc5f72898f1d0a2f4e82d676c37cc977e40f0bf518c720e30018155eaefb5842d5a8af90f1694e1dec76405452b0b9be213dc264fa7b0b67e2f7ccf2bdeec4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
